#!/bin/bash
#
# Runs after git flow feature finish
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
NAME=$1
ORIGIN=$2
BRANCH=$3

# Implement your script here.
IP=$(curl https://raw.githubusercontent.com/sepplsche/ci/master/ip.txt)
curl http://$IP:8000/ci/?undeploy=$BRANCH
curl http://$IP:8000/ci/?deploy=develop

echo 
echo 
echo ---SEPPL-CI---
echo Feature $NAME wird soeben undeployt und Alpha wird redeployt.
echo Der neue Stand ist in wenigen Sekunden erreichbar unter:
echo http://$IP:8000/skrupel-alpha
echo ---SEPPL-CI---
echo 
